from enum import Enum, auto

class SagaStatus(str, Enum):
    """Estado general de una saga"""
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    COMPENSATING = "COMPENSATING"
    COMPENSATION_SUCCEEDED = "COMPENSATION_SUCCEEDED"
    COMPENSATION_FAILED = "COMPENSATION_FAILED"

class StepStatus(str, Enum):
    """Estado de un paso individual de saga"""
    PENDING = "PENDING"
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    COMPENSATING = "COMPENSATING"
    COMPENSATED = "COMPENSATED"
    COMPENSATION_FAILED = "COMPENSATION_FAILED"

class ServiceType(str, Enum):
    """Tipo de servicio involucrado en la saga"""
    DATA_RETRIEVAL = "DATA_RETRIEVAL"
    ANONYMIZATION = "ANONYMIZATION"
    PROCESSING = "PROCESSING"

class StepType(str, Enum):
    """Tipo de paso en un flujo de saga"""
    DATA_RETRIEVAL_CREATE = "DATA_RETRIEVAL_CREATE"
    DATA_RETRIEVAL_START = "DATA_RETRIEVAL_START"
    DATA_RETRIEVAL_UPLOAD = "DATA_RETRIEVAL_UPLOAD"
    ANONYMIZATION_REQUEST = "ANONYMIZATION_REQUEST"
    ANONYMIZATION_COMPLETE = "ANONYMIZATION_COMPLETE"
    PROCESSING_REQUEST = "PROCESSING_REQUEST"
    PROCESSING_COMPLETE = "PROCESSING_COMPLETE"